[pytest]
# 1. Пути для импортов
pythonpath = .

# 2. Настройки запуска
# Мы оставили только те флаги, которые понимает ваш Selenium + Allure проект
addopts = --base-url https://mwtestconsultancy.co.uk -v --alluredir=allure-results

# 3. Пути к тестам
testpaths = temp_tests/UI_tests

# 4. Настройки логирования
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %H:%M:%S