[pytest]
# 1. Пути для импортов (чтобы pytest видел папки с кодом)
pythonpath = .

# 2. Настройки запуска (ВСЕ флаги в одной строке)
# --alluredir=allure-results : создает папку для отчета
# --timeout=90000 : увеличиваем время ожидания до 90 сек из-за VPN
# --screenshot=only-on-failure : делает скриншот только при падении
addopts = --browser chromium --base-url https://mwtestconsultancy.co.uk -v --screenshot=only-on-failure --output=test-results --alluredir=allure-results --timeout=90000

# 3. Пути к тестам
# Проверьте: если тесты лежат в папке tests, замените на testpaths = tests
testpaths = temp_tests/UI_tests

# 4. Настройки логирования (то, что вы видите в терминале)
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %H:%M:%S