name: UI and API Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Устанавливаем зависимости из вашего файла
          pip install -r requirements.txt
          # Явно доустанавливаем плагин, чтобы исключить ошибку со скриншота
          pip install pytest-playwright

      - name: Install Playwright Browsers
        # Команда install --with-deps обязательна для Ubuntu
        run: playwright install --with-deps

      - name: Run Tests
        # 1. Мы убрали --headless (в CI плагин сам включит этот режим)
        # 2. Запускаем через 'python -m pytest', это надежнее в CI
        run: python -m pytest --alluredir=allure-results
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
